language: python
cache: pip
python:
  - "3.4"
  - "2.7"
env:
  - REQ="Django>=1.8,<1.9"
  - REQ="Django>=1.9,<1.10"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $REQ django-modeltranslation
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
